// webAngular/src/app/core/footer/footer.component.ts
import { Component } from '@angular/core';

interface FooterLink {
  label: string;
  path: string;
}

@Component({
  selector: 'app-footer',
  standalone: false,
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  readonly year = new Date().getFullYear();

  readonly whatsappUrl =
    'https://wa.me/573112240535?text=Hola!%20Me%20interesa%20cotizar%20un%20evento%20con%20MS%20Eventos.';

  readonly footerLinks: FooterLink[] = [
    { label: 'Inicio',      path: '/' },
    { label: 'Sonido',      path: '/sonido' },
    { label: 'Artistas',    path: '/artistas' },
    { label: 'Ingeniería',  path: '/ingenieria' },
    { label: 'DJs',         path: '/djs' },
    { label: 'Galería',     path: '/galeria' },
  ];
}

<footer>
  <div class="footer-container">

    <div class="footer-grid">

      <div class="footer-col brand-col">
        <a routerLink="/" class="logo">
          <div class="logo-badge">
            <img src="assets/img/logos/logo ms.png" alt="ms Group" class="badge-img">
          </div>
          <div class="logo-text">
            <div class="logo-name">MS EVENTOS</div>
            <div class="logo-sub">soluciones profesionales</div>
          </div>
        </a>
        <p class="brand-desc">
          Llevamos tu evento al siguiente nivel con tecnología de vanguardia en sonido, pantallas LED, iluminación profesional y producción técnica integral.
        </p>
      </div>

      <div class="footer-col links-col">
        <h4 class="col-title">Navegación</h4>
        <ul class="footer-links">
          <li *ngFor="let link of footerLinks">
            <a [routerLink]="link.path" class="footer-link">
              {{ link.label }}
            </a>
          </li>
        </ul>
      </div>

      <div class="footer-col contact-col">
        <h4 class="col-title">Contacto</h4>
        <ul class="contact-info">
          <li>
            <span class="icon">
           <i class="fa-solid fa-location-dot" style="color: rgb(255, 255, 255);"></i>
            </span>
            <span>Bogotá, Colombia</span>
          </li>
          <li>
            <span class="icon">
              <i class="fa-solid fa-phone" style="color: rgb(255, 255, 255);"></i>
            </span>
            <a href="tel:+573112240535" class="contact-link">+57 311 224 0535</a>
          </li>
          <li>
            <span class="icon">
              <i class="fa-solid fa-envelope" style="color: rgb(255, 255, 255);"></i>
            </span>
            <a href="mailto:comercial@msgroup.com.co" class="contact-link">comercial@msgroup.com.co</a>
          </li>
        </ul>
        <a [href]="whatsappUrl" target="_blank" rel="noreferrer" class="cta-button">
          <img src="assets/img/logos/whatsapp.svg" alt="WhatsApp" class="icon-img" />
          Cotizar por WhatsApp
        </a>
      </div>

    </div>

    <div class="footer-bottom">
      <div class="bottom-inner">
        <span class="copyright">
          Copyright © {{ year }} MS EVENTOS. Todos los derechos reservados.
        </span>
        <span class="tags">
          ARRAY · LEDS &amp; BEAMS · PANTALLAS
        </span>
      </div>
    </div>

  </div>
</footer>

// webpageofficial/src/components/Footer.jsx
import { Link } from 'react-router-dom'
import { NAV_LINKS, waLink } from '../data/content.js'
import styles from './Footer.module.css'

export default function Footer() {
  return (
    <footer className={styles.footer}>
      <div className={styles.inner}>

        <div className={styles.top}>
          <Link to="/" className={styles.logo}>
            <div className={styles.logoBadge}>m:s</div>
            <div>
              <div className={styles.logoName}>MS EVENTOS</div>
              <div className={styles.logoSub}>soluciones profesionales</div>
            </div>
          </Link>

          <nav className={styles.links}>
            {NAV_LINKS.map(l => (
                <Link key={l.to} to={l.to} className={styles.link}>
                  {l.label}
                </Link>
            ))}
          </nav>
          <a
              href={waLink()}
              target="_blank"
              rel="noreferrer"
              className={styles.cta}
          >
            <img src="/src/assets/whatsapp.svg" alt="WhatsApp" style={{ width: 20, height: 20 }} />
            WhatsApp
          </a>

        </div>

        <div className={styles.bottom}>
          <span>Copyright © 2026 msgroup. Todos los derechos reservados.</span>
          <span>Desarrollado por: <a href="https://digital-veltrix.netlify.app/" target="_blank" rel="noopener noreferrer">Digital Veltrix</a></span>
          <span>ARRAY · LEDS&BEAMS · PANTALLA</span>
        </div>
      </div>
    </footer>
  )
}
